# Generated by Django 4.0 on 2022-08-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppoinMentData',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('mobile', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
